<?php 
    require_once("classes/Database.php");
    require_once("classes/Session.php");
    require_once("classes/Functions.php");
    require_once("classes/User.php");
    require_once("classes/Floor.php");
    require_once("classes/Flat.php");
    require_once("classes/Notice.php");
    require_once("classes/Water.php");
    require_once("classes/Query.php");
?>